### ISSUE TITLE
It not work

### ISSUE THREAD

**Issue by Piecrafty** [christin910/blooket-hack#2]
it does not work i just get the same thing how do i fix it
![Screenshot 2022-03-28 9 06 40 PM](https://user-images.githubusercontent.com/101902890/160518168-d65a5e28-8cac-4b9f-8ffa-0d25be08d57e.png)

**Comment by Piecrafty** [comment]
@PythonCoder910  plz help

**Comment by Piecrafty** [comment]
here is more of it 
![image](https://user-images.githubusercontent.com/101902890/160612228-a9d315fa-ef54-4157-9879-70aba8d9bbaa.png)

**Comment by PythonCoder910** [comment]
Ok I will update all the code in the project. Looking forward to u using it!
